### ISSUE TITLE
点击删除标签崩溃

### ISSUE THREAD

**Issue by chen8888** [pengyuantao/OnePush#16]
进入demo首页，不管是否点击设置标签，点击删除标签，程序崩溃。
log：
11-23 19:18:27.875 27452-27452/? D/dalvikvm: Late-enabling CheckJNI
11-23 19:18:27.925 27452-27452/com.peng.one.push1 D/ActivityThread: handleBindApplication:com.peng.one.push1
11-23 19:18:27.925 27452-27452/com.peng.one.push1 D/ActivityThread: setTargetHeapUtilization:0.75
11-23 19:18:27.925 27452-27452/com.peng.one.push1 D/ActivityThread: setTargetHeapMinFree:4194304
11-23 19:18:27.925 27452-27452/com.peng.one.push1 D/ActivityThread: setTargetHeapConcurrentStart:2097152
11-23 19:18:27.985 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 105 name: GeTui result: false
11-23 19:18:27.995 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 104 name: UMENG result: false
11-23 19:18:28.015 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 106 name: JPush result: false
11-23 19:18:28.025 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 101 name: XiaoMi result: false
11-23 19:18:28.035 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 103 name: MeiZu result: false
11-23 19:18:28.055 27452-27452/com.peng.one.push1 I/PushApplication: Register-> code: 107 name: HMSPush result: true
11-23 19:18:28.055 27452-27452/com.peng.one.push1 I/OneLog: current register platform is OnePush_HMSPush_107
11-23 19:18:28.055 27452-27452/com.peng.one.push1 I/OneLog: HMSPush--register()
11-23 19:18:28.055 27452-27452/com.peng.one.push1 I/AndroidRuntime: timezone is Asia/Shanghai
11-23 19:18:28.125 27452-27452/com.peng.one.push1 I/PushApplication: onCreate: isFlymeRom:false
11-23 19:18:28.125 27452-27452/com.peng.one.push1 V/HwPolicyFactory: : success to get AllImpl object and return....
11-23 19:18:28.135 27452-27452/com.peng.one.push1 V/HwWidgetFactory: : successes to get AllImpl object and return....
11-23 19:18:28.135 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
11-23 19:18:28.135 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve interface method 17451: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
11-23 19:18:28.135 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
11-23 19:18:28.135 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
11-23 19:18:28.135 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
11-23 19:18:28.135 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve interface method 17453: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
11-23 19:18:28.135 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
11-23 19:18:28.135 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
11-23 19:18:28.135 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve interface method 17457: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
11-23 19:18:28.135 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
11-23 19:18:28.145 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
11-23 19:18:28.145 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 692: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
11-23 19:18:28.145 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
11-23 19:18:28.145 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
11-23 19:18:28.145 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 714: Landroid/content/res/TypedArray;.getType (I)I
11-23 19:18:28.145 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
11-23 19:18:28.165 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.widget.FrameLayout.startActionModeForChild, referenced from method android.support.v7.widget.ActionBarContainer.startActionModeForChild
11-23 19:18:28.165 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 17946: Landroid/widget/FrameLayout;.startActionModeForChild (Landroid/view/View;Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
11-23 19:18:28.165 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6f at 0x0002
11-23 19:18:28.175 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
11-23 19:18:28.175 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 421: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
11-23 19:18:28.175 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
11-23 19:18:28.185 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
11-23 19:18:28.185 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 655: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
11-23 19:18:28.185 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
11-23 19:18:28.185 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
11-23 19:18:28.185 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve virtual method 657: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
11-23 19:18:28.185 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
11-23 19:18:28.195 27452-27452/com.peng.one.push1 E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
11-23 19:18:28.195 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve instanceof 182 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
11-23 19:18:28.195 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
11-23 19:18:28.255 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.support.v13.app.FragmentCompat.requestPermissions, referenced from method permissions.dispatcher.PermissionUtils.requestPermissions
11-23 19:18:28.255 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve static method 2628: Landroid/support/v13/app/FragmentCompat;.requestPermissions (Landroid/app/Fragment;[Ljava/lang/String;I)V
11-23 19:18:28.255 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0000
11-23 19:18:28.255 27452-27452/com.peng.one.push1 I/dalvikvm: Could not find method android.support.v13.app.FragmentCompat.shouldShowRequestPermissionRationale, referenced from method permissions.dispatcher.PermissionUtils.shouldShowRequestPermissionRationale
11-23 19:18:28.255 27452-27452/com.peng.one.push1 W/dalvikvm: VFY: unable to resolve static method 2629: Landroid/support/v13/app/FragmentCompat;.shouldShowRequestPermissionRationale (Landroid/app/Fragment;Ljava/lang/String;)Z
11-23 19:18:28.255 27452-27452/com.peng.one.push1 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0007
11-23 19:18:28.275 27452-27452/com.peng.one.push1 I/OneLog: token null
11-23 19:18:28.315 27452-27452/com.peng.one.push1 I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
                                                                OpenGL ES Shader Compiler Version: E031.24.02.07
                                                                Build Date: 01/15/15 Thu
                                                                Local Branch: 
                                                                Remote Branch: 
                                                                Local Patches: 
                                                                Reconstruct Branch: 
11-23 19:18:28.325 27452-27480/com.peng.one.push1 D/MSimTelephonyManager: mapDualCardSubID, input subscription = 0
11-23 19:18:28.325 27452-27480/com.peng.one.push1 D/MSimTelephonyManager: getDeviceId, subscription=0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: PartialUpdate status: Disabled
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Left Align: 0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Width Align: 0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Top Align: 0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Height Align: 0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Min ROI Width: 0
11-23 19:18:28.335 27452-27452/com.peng.one.push1 I/qdutils: Min ROI Height: 0
11-23 19:18:28.345 27452-27452/com.peng.one.push1 D/OpenGLRenderer: Enabling debug mode 0
11-23 19:18:28.425 27452-27452/com.peng.one.push1 I/OneLog: HMS connect success!
11-23 19:18:28.465 27452-27452/com.peng.one.push1 I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@42585630 time:218327094
11-23 19:18:28.465 27452-27452/com.peng.one.push1 I/OneLog: token com.huawei.hms.support.api.entity.push.TokenResp@428c4c20
11-23 19:18:28.485 27452-27500/com.peng.one.push1 I/OneLog: onToken() called with: context = [android.app.ReceiverRestrictedContext@428d4ba0], token = [0A000005566726A0300000898500CN01], bundle = [Bundle[{receiveType=1, deviceToken=0A000005566726A0300000898500CN01, device_token=[B@428d4d48, pushMsg=null, belongId=1}]]
11-23 19:18:28.495 27452-27452/com.peng.one.push1 I/TestPushReceiver: onCommandResult: OnePushCommand{type=TYPE_REGISTER, resultCode=200, token='0A000005566726A0300000898500CN01', extraMsg='null', error='null'}
11-23 19:18:28.495 27452-27452/com.peng.one.push1 I/OneLog: com.peng.one.push.ACTION_RECEIVE_COMMAND_RESULT--OnePushCommand{type=TYPE_REGISTER, resultCode=200, token='0A000005566726A0300000898500CN01', extraMsg='null', error='null'}
11-23 19:18:36.305 27452-27452/com.peng.one.push1 V/AudioManager: playSoundEffect   effectType: 0
11-23 19:18:36.305 27452-27452/com.peng.one.push1 V/AudioManager: querySoundEffectsEnabled...
11-23 19:18:36.315 27452-27452/com.peng.one.push1 I/OneLog: HMSPush--deleteTag(test)
11-23 19:18:36.315 27452-27452/com.peng.one.push1 D/AndroidRuntime: Shutting down VM
11-23 19:18:36.315 27452-27452/com.peng.one.push1 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41639e18)
11-23 19:18:36.325 27452-27452/com.peng.one.push1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.peng.one.push1, PID: 27452
                                                                    com.huawei.hms.support.api.push.PushException: delete tags failed
                                                                        at com.huawei.hms.support.api.push.a.a(PushTagManager.java:123)
                                                                        at com.huawei.hms.support.api.push.HuaweiPushApiImp.deleteTags(HuaweiPushApiImp.java:173)
                                                                        at com.peng.one.push.huawei.hms.HMSPushClient.deleteTag(HMSPushClient.java:129)
                                                                        at com.peng.one.push.core.OnePushContext.deleteTag(OnePushContext.java:177)
                                                                        at com.peng.one.push.OnePush.deleteTag(OnePush.java:69)
                                                                        at com.peng.one.push1.MainActivity.onClick(MainActivity.java:110)
                                                                        at android.view.View.performClick(View.java:4457)
                                                                        at android.view.View$PerformClick.run(View.java:18491)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: com.huawei.hms.support.api.push.PushException: no tag need to delete
                                                                        at com.huawei.hms.support.api.push.a.a(PushTagManager.java:117)
                                                                        at com.huawei.hms.support.api.push.HuaweiPushApiImp.deleteTags(HuaweiPushApiImp.java:173) 
                                                                        at com.peng.one.push.huawei.hms.HMSPushClient.deleteTag(HMSPushClient.java:129) 
                                                                        at com.peng.one.push.core.OnePushContext.deleteTag(OnePushContext.java:177) 
                                                                        at com.peng.one.push.OnePush.deleteTag(OnePush.java:69) 
                                                                        at com.peng.one.push1.MainActivity.onClick(MainActivity.java:110) 
                                                                        at android.view.View.performClick(View.java:4457) 
                                                                        at android.view.View$PerformClick.run(View.java:18491) 
                                                                        at android.os.Handler.handleCallback(Handler.java:733) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                        at dalvik.system.NativeStart.main(Native Method) 
11-23 19:18:37.855 27452-27452/com.peng.one.push1 I/Process: Sending signal. PID: 27452 SIG: 9

**Comment by pengyuantao** [comment]
QQ上已经说明，华为HMS不支持EMUI4.0以下的系统手机

**Comment by chen8888** [comment]
好的，回头测试一下，谢谢...
